### ISSUE TITLE
Tabellen übergreifende methoden

### ISSUE THREAD

**Issue by JonahKr** [atalantus/Wokabel-App#46]
## Task zur User Story *#5*
Hinzufügen von Tabellenübergreifenden Methoden.
* [x] Löschen der kompletten Datenbankinhalte
* [x] Prüfe: Gibt es inhalte in einer Tabelle?
* [x] Prüfe: Gibt es Inhalte in der Datenbank?
* [x] Beispiel Unit hinzufügen
* [x] ...

**Comment by JonahKr** [comment]
if(!dbadapter.checkforContentDatabase){
    Supergroup sp1=dbadapter.insertSupergroup(new Supergroup("Englisch",iconid);
    Subgroup sb1=dbadapter.insertSubgroup(new Subgroup("Unit 1", sp1.getId());
    dbadapter.insertVocable(new Vocable("hello",<"Hallo">,"Hello Jeff, how are you?",sb1.getId());
    dbadapter.insertVocable(new Vocable("bye",<"Tschüss">,"Bye Jeff. Have a nice day.",sb1.getId());
}
